# Generated by Django 5.2.2 on 2026-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_backfill_structured_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, db_column='NationalID', max_length=50, null=True),
        ),
    ]
