# Generated by Django 5.2.2 on 2026-05-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to='verifications/national_id/')),
                ('agricultural_card_image', models.ImageField(blank=True, null=True, upload_to='verifications/agricultural_card/')),
                ('transport_license_image', models.ImageField(blank=True, null=True, upload_to='verifications/transport_license/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
                'db_table': 'UserVerification',
            },
        ),
    ]
