# Generated by Django 5.2.2 on 2026-05-19 21:35

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_userverification'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "documents_verificationdocument" CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
