# Generated by Django 5.2.2 on 2026-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_active_and_master_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggested_price',
            field=models.IntegerField(blank=True, db_column='SuggestedPrice', null=True),
        ),
        migrations.DeleteModel(
            name='OfficialPrice',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
