# Generated by Django 5.2.2 on 2026-05-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficialPrice',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
