export {
  getNationalStats,
  getUsers,
  getPendingUsers,
  approveUser,
  rejectUser,
  requestInfo,
  getCategories,
  addCategory,
  updateCategory,
  deleteCategory,
  getProducts,
  addProduct,
  updateProduct,
  deleteProduct,
  generateReport,
} from '../models/adminModel'
