# Generated by Django 5.2.2 on 2026-05-04 23:14

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_verificationdocument_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdocument',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.ImageField(upload_to='verification_documents/%Y/%m/', validators=[apps.documents.models.validate_verification_image]),
        ),
    ]
