# Generated by Django 5.2.2 on 2026-05-05 00:51

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_verificationdocument_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.ImageField(upload_to=apps.documents.models.generate_uuid_filename, validators=[apps.documents.models.validate_verification_image]),
        ),
    ]
