import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import https from 'https';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const catalogPath = path.join(__dirname, '../shared/controlled-product-catalog.json');
const productsDir = path.join(__dirname, '../src/assets/products');

if (!fs.existsSync(productsDir)) {
  fs.mkdirSync(productsDir, { recursive: true });
}

// Remove old SVG placeholders
const oldFiles = fs.readdirSync(productsDir);
for (const file of oldFiles) {
  if (file.endsWith('.svg')) {
    fs.unlinkSync(path.join(productsDir, file));
  }
}

const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
const names = catalog.map(p => p.name);

// Fallback logic
names.push('default');

const downloadImage = (url, filepath) => {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return downloadImage(res.headers.location, filepath).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        reject(new Error(`Failed to get '${url}' (${res.statusCode})`));
        return;
      }
      const stream = fs.createWriteStream(filepath);
      res.pipe(stream);
      stream.on('finish', () => {
        stream.close();
        resolve(filepath);
      });
      stream.on('error', (err) => {
        fs.unlink(filepath, () => {});
        reject(err);
      });
    }).on('error', (err) => {
      reject(err);
    });
  });
};

const sanitize = (name) => name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');

const run = async () => {
  console.log(`Downloading ${names.length} images...`);
  
  const importsMap = [];
  const exportMap = [];

  for (let i = 0; i < names.length; i++) {
    const name = names[i];
    const key = sanitize(name);
    const filename = `${key}.jpg`;
    const filepath = path.join(productsDir, filename);
    const keyword = name === 'default' ? 'agriculture,food' : name.replace(/ /g, ',');
    
    // Using loremflickr mapping
    try {
      console.log(`Downloading ${key} from loremflickr...`);
      await downloadImage(`https://loremflickr.com/500/500/${encodeURIComponent(name)},food/all`, filepath);
      
      const varName = key.replace(/-([a-z])/g, (g) => g[1].toUpperCase()) + 'Img';
      importsMap.push(`import ${varName} from '../assets/products/${filename}';`);
      exportMap.push(`  '${key}': ${varName},`);
    } catch (e) {
      console.error(`Failed ${name}: ${e.message}`);
    }
  }

  // Generate the productImages.js
  const jsContent = `// Auto-generated by downloadImages.js\n\n${importsMap.join('\n')}\n\nconst productImages = {\n${exportMap.join('\n')}\n};\n\nexport const getProductImage = (productName) => {\n  if (!productName) return productImages.default;\n  const key = productName.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');\n  return productImages[key] || productImages.default;\n};\n\nexport default productImages;\n`;

  fs.writeFileSync(path.join(__dirname, '../src/utils/productImages.js'), jsContent);
  console.log('✅ Generated src/utils/productImages.js');
};

run().catch(console.error);
